---
layout_apply:
 host: 0.0.0.0
 port: 8003
 request:
  max_workers: 2
db:
 dbname: ApplyStatusDB
 user: user01
 host: localhost
 port: 5432
get_information:
 host: localhost
 port: 48889
 uri: cdim/api/v1
 specs:
  poweroff:
   polling:
    count: 15
    interval: 6
  connect:
   polling:
    count: 15
    interval: 6
  disconnect:
   polling:
    count: 15
    interval: 6
  timeout: 15
workflow_manager:
 host: 0.0.0.0
 port: 8008
 uri: cdim/api/v1
 extended-procedure:
  retry:
   default:
    interval: 5
    max_count: 5
  polling:
   count: 60
   interval: 30
 timeout: 60
hardware_control:
 host: localhost
 port: 48889
 uri: cdim/api/v1
 disconnect:
  retry:
   targets:
    - status_code: 503
      code: ER005BAS001
      interval: 2
      max_count: 2
    - status_code: 503
      code: ER005BAS002
      interval: 2
      max_count: 2
   default:
    interval: 2
    max_count: 2
  timeout: 30
 connect:
  retry:
   targets:
    - status_code: 503
      code: ER005BAS001
      interval: 2
      max_count: 2
    - status_code: 503
      code: ER005BAS002
      interval: 2
      max_count: 2
   default:
    interval: 2
    max_count: 2
  timeout: 30
 poweroff:
  retry:
   targets:
    - status_code: 503
      code: ER005BAS001
      interval: 2
      max_count: 2
    - status_code: 503
      code: ER005BAS002
      interval: 2
      max_count: 2
   default:
    interval: 2
    max_count: 2
  timeout: 30
 poweron:
  retry:
   targets:
    - status_code: 503
      code: ER005BAS001
      interval: 2
      max_count: 2
    - status_code: 503
      code: ER005BAS002
      interval: 2
      max_count: 2
   default:
    interval: 2
    max_count: 2
  timeout: 30
 isosboot:
  polling:
   count: 15
   interval: 6
   skip:
    - status_code: 400
      code: EF003BAS010
  request:
   timeout: 2
  timeout: 30
migration_procedure_generator:
 host: localhost
 port: 48889
 uri: cdim/api/v1
 timeout: 30
configuration_manager:
 host: localhost
 port: 48889
 uri: cdim/api/v1
 timeout: 30
server_connection:
 retry:
  interval: 3
  max_count: 5
message_broker:
 host: localhost
 port: 3500
 pubsub: layout_apply_apply
 topic: layout_apply_apply.completed
