CREATE TABLE IF NOT EXISTS  applystatus(
applyid varchar(10) PRIMARY KEY,
status varchar(12),
procedures jsonb,
applyresult jsonb,
rollbackprocedures jsonb,
startedat timestamp,
endedat timestamp,
canceledat timestamp,
executerollback boolean,
rollbackstatus varchar(12),
rollbackresult jsonb,
rollbackstartedat timestamp,
rollbackendedat timestamp,
resumeprocedures jsonb,
resumeresult jsonb,
processid int,
executioncommand text,
processstartedat text,
suspendedat timestamp,
resumedat timestamp
);